import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import HeroSection from "@/components/HeroSection";
import AboutSection from "@/components/AboutSection";
import PortfolioSection from "@/components/PortfolioSection";
import TestimonialSection from "@/components/TestimonialSection";
import ContactSection from "@/components/ContactSection";
import FooterSection from "@/components/FooterSection";
import PortfolioFull from "@/components/PortfolioFull";

const inter = Inter({ subsets: ["latin"] });

export default function PortfolioPage() {
  return (
    <>
      <Head>
        <title>Ogochuks || Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="mt-20">
          <PortfolioFull />
        </div>
        <FooterSection />
      </main>
    </>
  );
}
